apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mastodon.fullname" . }}-env
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
data:
  DB_HOST: {{ template "mastodon.postgresql.fullname" . }}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase }}
  DB_POOL: {{ .Values.sidekiq.concurrency | quote }}
  DB_PORT: {{ .Values.postgresql.service.port | quote }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername }}
  LOCAL_DOMAIN: {{ .Values.ingress.hostname }}
  REDIS_HOST: {{ template "mastodon.redis.fullname" . }}-master
  REDIS_PORT: {{ .Values.redis.master.service.port }}
  {{- if .Values.elasticsearch.enabled }}
  ES_ENABLED: "true"
  ES_HOST: "{{ template "mastodon.elasticsearch.fullname" . }}-master"
  {{- end }}
{{- range $key, $value := .Values.environment.public }}
  {{- if not (empty $value) }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
