apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mastodon.fullname" . }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.environment.secret }}
  {{ $key }}: "{{ $value | b64enc }}"
{{- end }}
